name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get install python3-setuptools
        sudo pip3 install numpy
        sudo pip3 install scikit-surprise
        sudo apt-get install mysql-server
        sudo apt-get install mysql-client
        sudo apt-get install libmysqlclient-dev
        sudo pip3 install -r requirements.txt
        
    - name: GitHub Action for Heroku
      uses: actions/heroku@1.0.0
